
services: 
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootadm
      - MYSQL_DATABASE=atividade-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=rootadm
    networks:
      - backtier
    volumes:
      - db-data:/etc/data

  app:
    build: 
      context: .
    ports:
      - 3001:3000
    networks:
      - backtier




networks:
  backtier:
    driver: bridge

volumes:
  db-data:
    driver: local